# Set chat_name to Intel chat name as it is dispalyed in game.
#
# green, yellow, red -- are the alert levels represented by corresponding notification sound.
# do not list the same systems in the different levels (well you can, but there is no good reason to)
#
# You can specify path to ChatLogs directory via 'logs_path' (if tool can't get it automatically)

watcher:
    system_map:
        green:
          - 'OJT-J3'
        yellow:
          - '8B-A4E'
        red:
          - 'RZ3O-K'
          - 'AV2-O'
          - '8SY-Q'
    chat_name: 'SomeNoneName.Intel'
    logs_path: '' # keep empty for autodetection;
